package memory_bank;
/*

 * This Java source file was generated by the Gradle 'init' task.
 */
import memory_bank.NotePad;

import java.util.*;

//package memory_bank;

public class App {

    public static void main(String[] args) {
        NotePad notepad = new NotePad();
    }
}
